//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClass_Clients
    {
        public int ID_GroupClassClients { get; set; }
        public int Class_ID { get; set; }
        public int Client_ID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public bool IsPresent { get; set; }
        public Nullable<bool> AttendanceStatus_Bit { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual GroupClasses GroupClasses { get; set; }
    }
}
 