//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupClasses()
        {
            this.GroupClass_Clients = new HashSet<GroupClass_Clients>();
        }
    
        public int ID_Class { get; set; }
        public string ClassName { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int MaxParticipants { get; set; }
        public int RegisteredClients { get; set; }
        public int Trainer_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupClass_Clients> GroupClass_Clients { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
